name: Andrea Baise.ro
description: As above
github: https://github.com/bigblindbais/baise.ro

# url: http://localhost:4000
url: "http://baise.ro"

markdown: kramdown
permalink: pretty
highlighter: pygments

folders:
  scripts: _scripts/
  ipynb: ipynb/

navigation: [ baise.ro, research, code, weblog, about ]
exclude: [ 'fabfile', '*.pyc' ]
gems: [ 'jekyll/scholar' ]

scholar:
  # style: chicago-fullnote-bibliography
  # bibliography_template: <abbr>[{{key}}]</abbr>{{reference}}
  bibliography_template: bib

defaults:
  -
    scope:
      path: ""
    values:
      author: "Andrea Baisero"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: page
      icon: fa-bookmark
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: post
      permalink: /weblog/:title
      icon: fa-pencil
